name: Install guunits
description: Installs guunits in standard paths on the system

runs:
  using: 'composite'

  steps:
    - name: Clone guunits
      uses: actions/checkout@v2
      with:
          repository: mipalgu/guunits
          path: guunits

    - name: Install guunits
      if: ${{ runner.os == 'Windows' }}
      run: |
          cd guunits/guunits
          cmake -B .build
          cmake --build .build --config Release
          cmake --install .build
      shell: pwsh

    - name: Install guunits
      if: ${{ runner.os == 'Linux' || runner.os == 'macOS' }}
      run: |
          cd guunits/guunits
          cmake -B .build
          cmake --build .build --config Release
          cmake --install .build
      shell: bash

    - name: Add Environment Variables
      if: ${{ runner.os == 'Windows' }}
      run: |
        $env:PKG_CONFIG_PATH = "C:/Program Files (x86)/guunits/lib/pkgConfig;" + $env:PKG_CONFIG_PATH
        $env:LIBRARY_PATH = "C:/Program Files (x86)/guunits/lib;" + $env:LIBRARY_PATH
        $env:CPATH = "C:/Program Files (x86)/guunits/lib;" + $env:CPATH
        echo "{PKG_CONFIG_PATH}={$env:PKG_CONFIG_PATH}" | Out-File -FilePath $env:GITHUB_ENV -Append
        echo "{CPATH}={$env:CPATH}" | Out-File -FilePath $env:GITHUB_ENV -Append
        echo "{LIBRARY_PATH}={$env:LIBRARY_PATH}" | Out-File -FilePath $env:GITHUB_ENV -Append
      shell: pwsh
